# Generated by Django 3.0.7 on 2020-09-27 16:47

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import faicon.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блока')),
                ('close', models.BooleanField(default=False, verbose_name='Свернуть блок')),
                ('order', models.SmallIntegerField(db_index=True, default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Мой раздел',
                'verbose_name_plural': 'Мои разделы',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='TableCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocktablecat', to='cardapp.CreateBlock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Категория таблицы',
                'verbose_name_plural': 'Категории таблицы',
            },
        ),
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', embed_video.fields.EmbedVideoField(default='', help_text='Скопируйте и вставьте ссылку с youtube', verbose_name='Вставьте ссылку')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockvideos', to='cardapp.CreateBlock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='TableItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.SmallIntegerField(default=0)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='tableitems', to='cardapp.TableCategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Содержимое таблицы',
                'verbose_name_plural': 'Содержимое таблицы',
            },
        ),
        migrations.CreateModel(
            name='CreateLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Максимально 100 символов', max_length=100, verbose_name='Название')),
                ('status', models.IntegerField(choices=[(1, 'Обычная ссылка'), (2, 'Электронная почта'), (3, 'Номер телефона')], default=1, verbose_name='Тип ссылки')),
                ('url', models.CharField(help_text='Вставьте ссылку с пртоколом http:// или https://, если выбран тип электронной почты или телефона, то просто впишите вашу почту или номер телефона', max_length=900, verbose_name='Ссылка')),
                ('icon', faicon.fields.FAIconField(help_text='Выберите иконку', max_length=50, verbose_name='Иконка')),
                ('color_icon', colorfield.fields.ColorField(default='#FFF', help_text='Выберите цвет иконки', max_length=18, verbose_name='Цвет иконки')),
                ('color_bg', colorfield.fields.ColorField(default='#FF0000', help_text='Выберите цвет фона', max_length=18, verbose_name='Цвет фона')),
                ('order', models.SmallIntegerField(blank=True, db_index=True, default=0, help_text='Номер позиции в очереди', verbose_name='Позиция')),
                ('choose', models.BooleanField(default=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocklinks', to='cardapp.CreateBlock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Моя ссылка',
                'verbose_name_plural': 'Мои ссылки',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='CreateFaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.SmallIntegerField(db_index=True, default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockfaq', to='cardapp.CreateBlock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Вопрос-ответ',
                'verbose_name_plural': 'Вопросы-ответы',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='CardProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='images/%Y/%m/%d')),
                ('title', models.CharField(blank=True, max_length=35)),
                ('description', models.CharField(blank=True, max_length=81)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_bg', colorfield.fields.ColorField(default='#FF0000', help_text='Выберите цвет фона', max_length=18, verbose_name='Цвет фона')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='AddImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(help_text='Рекомендуем добавлять картинки одного размера', upload_to='images/%Y/%m/%d', verbose_name='Загрузите картинку')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockimages', to='cardapp.CreateBlock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
