# Generated by Django 3.0.7 on 2020-12-06 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cardapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableitems',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tableitems', to='cardapp.TableCategory'),
        ),
        migrations.AlterField(
            model_name='tableitems',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
